# Generated by Django 5.2 on 2025-05-11 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FINANCIAL", "Financial Support"),
                            ("TICKET", "Ticket Support"),
                            ("REGISTER", "Registration Support"),
                        ],
                        help_text="نوع پشتیبانی مرتبط با تیکت",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("PENDING", "Pending"),
                            ("ANSWERED", "Answered"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bootcamp",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر مقدار نداشته باشه، تیکت عمومی است.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Bootcamp_Ticket",
                        to="orders.bootcamp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CustomUser_Ticket",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("attachment", models.FileField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CustomUser_Sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ticket_TicketMessage",
                        to="tickets.ticket",
                    ),
                ),
            ],
        ),
    ]
