# Generated by Django 5.2 on 2025-05-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="role",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal User"),
                    ("FINANCIAL", "Financial Support"),
                    ("TICKET", "Ticket Support"),
                    ("REGISTER", "Registration Support"),
                    ("SUPERUSER", "Super User"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
