# Generated by Django 5.2 on 2025-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="support_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No Access"),
                    ("FINANCIAL", "Financial"),
                    ("TICKET", "Ticket"),
                    ("REGISTER", "Register"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal User"),
                    ("SUPPORT", "Support User"),
                    ("SUPERUSER", "Super User"),
                ],
                default="NORMAL",
                max_length=10,
            ),
        ),
    ]
